"apiVersion": |-
  scheduling.k8s.io/v1
"description": |-
  Used for pods that are easily preempted and unimportant.
"kind": |-
  PriorityClass
"metadata":
  "name": |-
    very-low
  "selfLink": |-
    /apis/scheduling.k8s.io/v1/priorityclasses/very-low
"value": !!int |-
  10
