name: volcano-admission
home: paddleflow
version: 0.0.15-rcbsxa
appVersion: 0.0.15-rcbsxa
apiVersion: v1
description: paddleflow volcano-admission.
sources:
- paddleflow
maintainers:
- name: pf-op
  email: paddleflow@paddle.com
