apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
    name: "pytorch-dist-sendrecv"
spec:
    pytorchReplicaSpecs:
        Master:
            replicas: 1
            restartPolicy: Never
            template:
                spec:
                    containers:
                        - name: pytorch
                          command:
                              - /bin/sh
                              - -c
                              - sleep 10
                          image: paddleflow/pytorch-dist-sendrecv-test:1.12.0
        Worker:
            replicas: 1
            restartPolicy: Never
            template:
                spec:
                    containers:
                        - name: pytorch
                          command:
                              - /bin/sh
                              - -c
                              - sleep 10
                          image: paddleflow/pytorch-dist-sendrecv-test:1.12.0