apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: sparkName
  namespace: default
spec:
  driver:
    serviceAccount:
    terminationGracePeriodSeconds: 30
  executor:
    terminationGracePeriodSeconds: 30
  image:
  imagePullPolicy: IfNotPresent
  mainApplicationFile:
  mainClass:
  mode: cluster
  restartPolicy:
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 5
    type: Never
  sparkVersion: 3.0.0
  type: Scala
  batchSchedulerOptions:
    queue:
    priorityClass: