apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcJobName
spec:
  minAvailable: 2
  schedulerName: volcano
  priorityClassName: normal
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 2
      name: "task"
      template:
        metadata:
          name: templateName
        spec:
          containers:
            - image: collective-container
              imagePullPolicy: IfNotPresent
              name: defaultContainer
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
      policies:
        - event: TaskCompleted
          action: CompleteJob
