apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcJobName
spec:
  minAvailable: 3
  schedulerName: volcano
  priorityClassName: normal
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "ps"
      ports:
        - ps-port: 8001
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: ps
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure
    - replicas: 2
      name: "worker"
      ports:
        - worker-port: 8001
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: worker
              resources:
                requests:
                  cpu: "1"
          restartPolicy: Never
      policies:
        - event: TaskCompleted
          action: CompleteJob
