apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcJobName
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: normal
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "task"
      template:
        metadata:
          name: pod
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: container
              resources:
                requests:
                  cpu: "1"
          restartPolicy: Never
      policies:
        - event: TaskCompleted
          action: CompleteJob
