init_cluster:
  affinity: {}
  annotations:
    reloader.stakater.com/auto: 'true'
  args:
  - '"/job/main.sh installpv"'
  chart_config_volumes:
    configMaps:
      conf:
        name: conf
    secrets: {}
  cluster_existing_volumes:
    configMaps: {}
    secrets: {}
  command:
  - /bin/bash -c
  config_msg:
  - config_name: main.sh
    mountPath: /job/main.sh
    volName: conf
  - config_name: config
    mountPath: /job/config
    type: binaryData
    volName: conf
  - config_name: local-pv.yaml
    mountPath: /job/local-pv.yaml
    type: binaryData
    volName: conf
  cronjob_msg: {}
  dnsPolicy: ClusterFirst
  enable: true
  hostAliases: {}
  hostNetwork: false
  image: iregistry.paddleflow-int.com/paddleflow/centos7-shelljob
  imagePullPolicy: IfNotPresent
  imageTag: '1.0'
  init_container_msg: {}
  job_msg:
    activeDeadlineSeconds: 120
    backoffLimit: 10
    completions: 1
    parallelism: 1
    ttlSecondsAfterFinished: 600
  labels: {}
  livenessProbe:
    content:
      httpGet:
        path: /healthz
        port: https
        scheme: HTTPS
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  logExporter:
    enable: false
    port: 9273
    telegraf:
      agent:
        debug: false
        flush_interval: 5s
        interval: 3s
        metric_batch_size: 1000
        metric_buffer_limit: 10000
      input:
      output:
        buckets: '[0.0, 201.0, 312.0, 401.0, 405.0, 501.0]'
        period: 30s
  name: init-cluster
  nodeSelector: {}
  persistence: {}
  podAnnotations: {}
  podSecurityContext: {}
  readinessProbe:
    content:
      httpGet:
        path: /healthz
        port: https
        scheme: HTTPS
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicas: 1
  resources: {}
  restartPolicy: OnFailure
  secret: {}
  secret_msg: []
  securityContext:
    privileged: false
  service:
    clusterIP: ''
    extra_usr_define_services: {}
    ports: {}
    service_domain: ''
    type: ClusterIP
  serviceAccount: {}
  serviceName: ''
  sidecar_container_msg: []
  special_env: {}
  startupProbe:
    content:
      httpGet:
        path: /healthz
        port: https
        scheme: HTTPS
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  strategy: {}
  paddleflow_node_affinity: {}
  tolerations: []
  type: shelljob
  usr_define_msg: {}
out_depend_msg: {}
product_name: init-cluster
total_ports: {}
version: 0.0.24-17335360
