{{- if .Values.km_volcano.enable -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volcano-admission
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volcano-admission
rules:
  - apiGroups: [""]
    resources: ["configmaps", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "create", "update"]
  # Rules below is used generate admission service secret
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/approval"]
    verbs: ["create", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch"]
  - apiGroups: ["scheduling.incubator.k8s.io", "scheduling.volcano.sh"]
    resources: ["queues"]
    verbs: ["get", "list"]
  - apiGroups: ["scheduling.incubator.k8s.io", "scheduling.volcano.sh"]
    resources: ["elasticresourcequotas", "elasticresourcequotas/status"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  - apiGroups: ["scheduling.incubator.k8s.io", "scheduling.volcano.sh"]
    resources: ["podgroups"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volcano-admission-role
subjects:
  - kind: ServiceAccount
    name: volcano-admission
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: volcano-admission
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: volcano-admission
  name: volcano-admission
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volcano-admission
  template:
    metadata:
      labels:
        app: volcano-admission
    spec:
      serviceAccount: volcano-admission
      {{- if .Values.volcano.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.volcano.image_pull_secret }}
      {{- end }}
      containers:
        - args:
            - --tls-cert-file=/admission.local.config/certificates/tls.crt
            - --tls-private-key-file=/admission.local.config/certificates/tls.key
            - --ca-cert-file=/admission.local.config/certificates/ca.crt
            - --webhook-namespace={{ .Release.Namespace }}
            - --webhook-service-name=volcano-admission-service
            - --logtostderr
            - --port={{.Values.volcano.admission_port}}
            - -v=6
            - --nvidia-mps-dev-volume-host-path=/dev/shm
            - --nvidia-mps-dev-volume-container-path=/dev/shm
            - --nvidia-cgpu-volume-host-path=/baidu-cgpu
            - --nvidia-cgpu-volume-container-path=/home/baidu-cgpu
            - --nvidia-lib-cuda-volume-host-path=/opt/baidu-cgpu/lib64/libcuda.so.1
            - --nvidia-lib-cuda-volume-centos-container-path=/usr/lib64/libcuda.so.1
            - --nvidia-lib-cuda-volume-ubuntu-container-path=/usr/lib/x86_64-linux-gnu/libcuda.so.1
            - --nvidia-lib-cuda-original-volume-host-path=/usr/lib64/libcuda.so.1
            - --nvidia-lib-cuda-original-volume-container-path=/usr/lib64/libcuda_original.so
            - --nvidia-libml-volume-host-path=/usr/lib64/libnvidia-ml.so
            - --nvidia-libml-volume-centos-container-path=/usr/lib64/libnvidia-ml.so.1
            - --nvidia-libml-volume-ubuntu-container-path=/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
            - --nvidia-libml-original-volume-host-path=/usr/lib64/libnvidia-ml.so
            - --nvidia-libml-original-volume-container-path=/usr/lib64/libnvidia-ml_original.so
            - 2>&1
          image: {{.Values.km_volcano.admission_image_name}}
          imagePullPolicy: IfNotPresent
          name: admission
          volumeMounts:
            - mountPath: /admission.local.config/certificates
              name: admission-certs
              readOnly: true
      volumes:
        - name: admission-certs
          secret:
            defaultMode: 420
            secretName: {{.Values.volcano.admission_secret_name}}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: volcano-admission
  name: volcano-admission-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{.Values.volcano.admission_port}}
  selector:
    app: volcano-admission
  sessionAffinity: None

---
apiVersion: batch/v1
kind: Job
metadata:
  name: volcano-admission-init
  namespace: {{.Values.volcano.volcano_namespace}}
  labels:
    app: volcano-admission-init
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: volcano-admission
      restartPolicy: Never
      containers:
        - name: main
          image: {{.Values.km_volcano.admission_image_name}}
          imagePullPolicy: IfNotPresent
          command: ["./gen-admission-secret.sh", "--service", "volcano-admission-service", "--namespace",
                    "{{ .Release.Namespace }}", "--secret", "{{.Values.volcano.admission_secret_name}}"]

{{- end -}}