---
apiVersion: scheduling.k8s.io/v1
description: Used for system critical pods that must not be moved from their current node.
kind: PriorityClass
metadata:
  name: very-high
  selfLink: /apis/scheduling.k8s.io/v1/priorityclasses/very-high
value: 2000
---
apiVersion: scheduling.k8s.io/v1
description: Used for critical pods that must not be moved from their current node.
kind: PriorityClass
metadata:
  name: high
  selfLink: /apis/scheduling.k8s.io/v1/priorityclasses/high
value: 1000

---
apiVersion: scheduling.k8s.io/v1
description: Used for normal pods.
kind: PriorityClass
metadata:
  name: normal
  selfLink: /apis/scheduling.k8s.io/v1/priorityclasses/normal
value: 100
globalDefault: true
---
apiVersion: scheduling.k8s.io/v1
description: Used for low-priority Pods that are easily preempted.
kind: PriorityClass
metadata:
  name: low
  selfLink: /apis/scheduling.k8s.io/v1/priorityclasses/low
value: 50

---
apiVersion: scheduling.k8s.io/v1
description: Used for pods that are easily preempted and unimportant.
kind: PriorityClass
metadata:
  name: very-low
  selfLink: /apis/scheduling.k8s.io/v1/priorityclasses/very-low
value: 10