{{- if .Values.spark_operator.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkoperator
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v3.0.0-v1beta2
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
      app.kubernetes.io/version: v3.0.0-v1beta2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v3.0.0-v1beta2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/cluster-role
                operator: NotIn
                values:
                - slave
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/cluster-role
                operator: In
                values:
                - master-no-compute
      serviceAccountName: sparkoperator
      volumes:
      - name: webhook-certs
        secret:
          secretName: spark-webhook-certs
      containers:
      - name: sparkoperator
        image: {{ .Values.spark_operator.image }}
        imagePullPolicy: Always
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook-certs
        ports:
        - containerPort: 8080
        args:
        - -logtostderr
        - -v=2
        - -enable-webhook=true
        - -enable-resource-quota-enforcement=true
        - -leader-election=true
        - -leader-election-lock-name=spark-operator-ha-lock
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sparkoperator-init
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v3.0.0-v1beta2
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v3.0.0-v1beta2
    spec:
      serviceAccountName: sparkoperator
      restartPolicy: Never
      containers:
      - name: main
        image: {{ .Values.spark_operator.image }}
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/gencerts.sh", "-p"]
---
kind: Service
apiVersion: v1
metadata:
  name: spark-webhook
  namespace: spark-operator
spec:
  ports:
    - port: 443
      targetPort: 8080
      name: webhook
  selector:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v3.0.0-v1beta2
{{- end -}}
