{{- if .Values.volcano_admission_init.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  #文件里的所有volcano-admission-init、volcano_admission_init都替换成实际名称
  name: {{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}
  labels:
    app: {{ template "volcano-admission-init.volcano_admission_init.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: '{{ $.Release.Service }}'
    app.kubernetes.io/instance: '{{ $.Release.Name }}'
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version }}'
    app.kubernetes.io/name: '{{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}'
    {{- with .Values.volcano_admission_init.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    {{- with .Values.volcano_admission_init.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  {{- with .Values.volcano_admission_init.job_msg.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with .Values.volcano_admission_init.job_msg.completions }}
  completions: {{ . }}
  {{- end}}
  {{- with .Values.volcano_admission_init.job_msg.parallelism }}
  parallelism: {{ . }}
  {{- end}}
  {{- with .Values.volcano_admission_init.job_msg.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end}}
  {{- with .Values.volcano_admission_init.job_msg.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end}}
  {{- with .Values.volcano_admission_init.job_msg.selector }}
  selector:
    app.kubernetes.io/managed-by: '{{ $.Release.Service }}'
    app.kubernetes.io/instance: '{{ $.Release.Name }}'
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version }}'
    app.kubernetes.io/name: '{{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}'
{{ toYaml . | indent 4 }}
  {{- end}}
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: '{{ $.Release.Service }}'
        app.kubernetes.io/instance: '{{ $.Release.Name }}'
        helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version }}'
        app.kubernetes.io/name: '{{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}'
    spec:
      {{- if .Values.volcano_admission_init.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ template "volcano-admission-init.volcano_admission_init.fullname_registry" . }}
      {{- end }}

      {{- if or $.Values.volcano_admission_init.affinity $.Values.volcano_admission_init.paddleflow_node_affinity }}
    {{ $affinity := index $.Values.volcano_admission_init "affinity" | default dict }}
      affinity:
        {{- if or $affinity.nodeAffinity $.Values.volcano_admission_init.paddleflow_node_affinity }}
        nodeAffinity:
          {{- if $affinity.nodeAffinity }}
            {{- if $affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              {{- range $i, $matchExpression := $affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
            - matchExpressions:
{{ toYaml $matchExpression.matchExpressions | indent 16 }}
                {{- if eq 0 $i}}
                  {{- /* add paddleflow_node_affinity if exists */}}
                  {{- with $.Values.volcano_admission_init.paddleflow_node_affinity }}
                    {{- if $.Values.volcano_admission_init.paddleflow_node_affinity.nodeAffinity }}
                      {{- $paddleflow_matchExpression := (index (index $.Values.volcano_admission_init.paddleflow_node_affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms 0).matchExpressions 0) | default dict }}
                - key: {{ $paddleflow_matchExpression.key }}
                  operator: {{ $paddleflow_matchExpression.operator }}
                  values:
                      {{- range $i, $value := $paddleflow_matchExpression.values}}
                    - {{ $value | quote }}
                      {{- end }}
                    {{- end }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- else if $.Values.volcano_admission_init.paddleflow_node_affinity }}
          requiredDuringSchedulingIgnoredDuringExecution:
{{ toYaml $.Values.volcano_admission_init.paddleflow_node_affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution |indent 12 }}
            {{- end }}
          {{- else if $.Values.volcano_admission_init.paddleflow_node_affinity }}
          requiredDuringSchedulingIgnoredDuringExecution:
{{ toYaml $.Values.volcano_admission_init.paddleflow_node_affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution |indent 12 }}
          {{- end }}
          {{- if $affinity.nodeAffinity }}
            {{- with $affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution}}
          preferredDuringSchedulingIgnoredDuringExecution:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- end}}
        {{- end }}
        {{- with $affinity.podAffinity }}
        podAffinity:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with $affinity.podAntiAffinity }}
        podAntiAffinity:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with $affinity.nodeAntiAffinity }}
        nodeAntiAffinity:
{{ toYaml . | indent 10 }}
        {{- end }}
      {{- end }}


      {{- with .Values.volcano_admission_init.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.volcano_admission_init.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.volcano_admission_init.serviceAccount }}
      serviceAccountName: {{.Values.volcano_admission_init.serviceAccount}}
      {{- end }}
      {{- with .Values.volcano_admission_init.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}{{with .name}}-{{ . }}{{end}}
        image: "{{ .Values.volcano_admission_init.image }}:{{ .Values.volcano_admission_init.imageTag }}"
        imagePullPolicy: {{ .Values.volcano_admission_init.imagePullPolicy | quote }}
        {{- if .Values.volcano_admission_init.command }}
        command:
{{ toYaml .Values.volcano_admission_init.command | indent 8 }}
        {{- end }}
        {{- if .Values.volcano_admission_init.args }}
        args:
{{ toYaml .Values.volcano_admission_init.args | indent 8 }}
        {{- end }}
        {{- with .Values.volcano_admission_init.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{-  with .Values.volcano_admission_init.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        #服务的环境变量，list形式，根据服务情况增加或删减
        env:
        #container_envs list
        #注意：这里的name跟后面volumes里name是一一对应的
        volumeMounts:
        {{- range $index, $pvc_message := .Values.volcano_admission_init.volumeMounts }}
        {{- range $key, $value := $pvc_message}}
        {{- if eq "name" $key }}
        - name: {{ $value }}
        {{- end }}
        {{- end }}
        {{- range $key, $value := $pvc_message}}
        {{- if ne "name" $key }}
          {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- range $index, $pvc_message := .Values.volcano_admission_init.config_msg }}
          {{- if $pvc_message.source }}
            {{-  if eq $pvc_message.source "cluster-existing" }}
        - name: {{$pvc_message.volName}}
          #容器里配置文件存放路径
          mountPath: {{ $pvc_message.mountPath }}
          #容器里配置文件名称
          subPath: {{ $pvc_message.subPath }}
            {{- end }}
          {{- else }}
        - name: {{$pvc_message.volName}}
          #容器里配置文件存放路径
          mountPath: {{ $pvc_message.mountPath }}
          #容器里配置文件名称
          subPath: {{ $pvc_message.config_name }}
          {{- end }}
        {{- end }}
        {{- range $index, $pvc_message := .Values.volcano_admission_init.secret_msg }}
          {{- if $pvc_message.source }}
            {{-  if eq $pvc_message.source "cluster-existing" }}
        - name: {{$pvc_message.volName}}
          #容器里配置文件存放路径
          mountPath: {{ $pvc_message.mountPath }}
          #容器里配置文件名称
          subPath: {{ $pvc_message.subPath }}
            {{- end }}
          {{- else }}
        - name: {{$pvc_message.volName}}
          #容器里配置secret存放路径
          mountPath: {{ $pvc_message.mountPath }}
          #容器里配置secret名称
          subPath: {{ $pvc_message.secret_name }}
          {{- end }}
        {{- end }}
      initContainers:
      {{- range .Values.volcano_admission_init.init_container_msg }}
      - name: {{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}{{with .name}}-{{ . }}{{else}}-initcontainer{{end}}
        image: "{{ .image }}:{{ .imageTag }}"
        imagePullPolicy: {{ .imagePullPolicy | quote }}
        {{- with .lifecycle }}
        lifecycle:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with .command }}
        command:
{{ toYaml . | indent 8 }}
        {{- end }}
        {{- with .args }}
        args:
{{ toYaml . | indent 8 }}
        {{- end }}
        {{- with .securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{-  with .resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        #服务的环境变量，list形式，根据服务情况增加或删减
        env:
        #init_container_envs list
        #注意：这里的name跟后面volumes里name是一一对应的
        volumeMounts:
        {{- range $index, $pvc_message := .volumeMounts }}
        - name: {{ $pvc_message.name }}
        {{- range $key, $value := $pvc_message}}
        {{- if ne "name" $key }}
          {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- range $index, $pvc_message := .config_msg }}
          {{- if $pvc_message.source }}
            {{- if eq $pvc_message.source "cluster-existing" }}
        - name: {{$pvc_message.volName}}
          #容器里配置文件存放路径
          mountPath: {{ $pvc_message.mountPath }}
          #容器里配置文件名称
          subPath: {{ $pvc_message.subPath }}
            {{- end }}
          {{- else }}
        - name: {{$pvc_message.volName}}
          #容器里配置文件存放路径
          mountPath: {{ $pvc_message.mountPath }}
          #容器里配置文件名称
          subPath: {{ $pvc_message.config_name }}
          {{- end }}
        {{- end }}
        {{- range $index, $pvc_message := .secret_msg }}
        - name: {{$pvc_message.volName}}
          #容器里配置secret存放路径
          mountPath: {{ $pvc_message.mountPath }}
          #容器里配置secret名称
          subPath: {{ $pvc_message.secret_name }}
        {{- end }}
      {{- end }}
      volumes:
      {{- range $volume_name, $volume_msg := .Values.volcano_admission_init.persistence }}
      - name: {{ $volume_name }}
      {{- if $volume_msg.enabled }}
        persistentVolumeClaim:
        {{- if $volume_msg.publicPvc }}
          claimName: {{ $volume_msg.publicPvcName }}
        {{- else }}
          claimName: {{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}-{{ $volume_name }}
        {{- end }}
      {{- else if $volume_msg.emptyDir }}
        emptyDir:
          {{- if $volume_msg.emptyDirMedium  }}
          medium: {{ $volume_msg.emptyDirMedium }}
          {{- end }}
      {{- else }}
        hostPath:
          path: {{ printf "%s%s" $volume_msg.hostPath $volume_msg.hostPathSplice }}
          {{- with $volume_msg.hostPathType }}
          type: {{ . }}
          {{- else }}
          type: DirectoryOrCreate
          {{- end }}
      {{- end }}
      {{- end }}
      # 集群已存在的configMap和secret
      {{- with .Values.volcano_admission_init.cluster_existing_volumes.configMaps }}
        {{- range $name, $cm := . }}
      - name: {{ $name }}
        configMap:
          name: {{ $cm.name }}
          {{- if $cm.defaultMode }}
          defaultMode: {{ $cm.defaultMode }}
          {{- end}}
        {{- end}}
      {{- end}}
      {{- with .Values.volcano_admission_init.cluster_existing_volumes.secrets }}
        {{- range $name, $secret := . }}
      - name: {{ $name }}
        secret:
          secretName: {{ $secret.name }}
          {{- if $secret.defaultMode }}
          defaultMode: {{ $secret.defaultMode }}
          {{- end}}
        {{- end}}
      {{- end}}
      {{- with .Values.volcano_admission_init.chart_config_volumes.configMaps }}
        {{- range $name, $cm := . }}
      - name: {{ $name }}
        configMap:
          name: {{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}
          {{- if $cm.defaultMode }}
          defaultMode: {{ $cm.defaultMode }}
          {{- end}}
        {{- end}}
      {{- end}}
      {{- with .Values.volcano_admission_init.chart_config_volumes.secrets }}
        {{- range $name, $secret := . }}
      - name: {{ $name }}
        secret:
          secretName: {{ template "volcano-admission-init.volcano_admission_init.fullname" $ }}
          {{- if $secret.defaultMode }}
          defaultMode: {{ $secret.defaultMode }}
          {{- end}}
        {{- end}}
      {{- end}}
      restartPolicy: {{ .Values.volcano_admission_init.restartPolicy }}
{{- end }}
