FROM paddelflow/pfs-csi-plugin-arm:base

RUN echo "Asia/shanghai" > /etc/timezone
ENV WORKDIR /home/paddleflow
ADD  bin/csi-plugin $WORKDIR/csi-plugin
ADD  bin/pfs-fuse $WORKDIR/pfs-fuse
ADD  bin/cache-worker $WORKDIR/cache-worker

WORKDIR /home/paddleflow