out_depend_msg: {}
product_name: volcano-admission-init
total_ports: {}
version: 0.0.4-rc0qx8
volcano_admission_init:
  affinity: {}
  annotations:
    reloader.stakater.com/auto: 'false'
  args: []
  chart_config_volumes:
    configMaps: {}
    secrets: {}
  cluster_existing_volumes:
    configMaps: {}
    secrets: {}
  command:
  - ./gen-admission-secret.sh
  - --service
  - volcano-admission-service
  - --namespace
  - volcano-system
  - --secret
  - volcano-admission-secret
  config_msg: []
  cronjob_msg: {}
  dnsPolicy: ClusterFirst
  enable: true
  hostAliases: {}
  hostNetwork: false
  image: paddleflow/vc-webhook-manager
  imagePullPolicy: IfNotPresent
  imageTag: '20220517_1652753373325'
  init_container_msg: {}
  job_msg:
    activeDeadlineSeconds: 120
    backoffLimit: '50'
    completions: '1'
    parallelism: '1'
    restartPolicy: OnFailure
    ttlSecondsAfterFinished: 100
  labels:
    app: volcano-admission-init
  livenessProbe:
    content:
      httpGet:
        path: /healthz
        port: https
        scheme: HTTPS
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  logExporter:
    enable: false
    port: 9273
    telegraf:
      agent:
        debug: false
        flush_interval: 5s
        interval: 3s
        metric_batch_size: 1000
        metric_buffer_limit: 10000
      input: null
      output:
        buckets: '[0.0, 201.0, 312.0, 401.0, 405.0, 501.0]'
        period: 30s
  name: volcano-admission-init
  nodeSelector: {}
  persistence: {}
  podAnnotations: {}
  podSecurityContext: {}
  readinessProbe:
    content:
      httpGet:
        path: /healthz
        port: https
        scheme: HTTPS
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicas: 1
  resources: {}
  restartPolicy: OnFailure
  secret: {}
  secret_msg: []
  securityContext:
    privileged: false
  service:
    clusterIP: ''
    extra_usr_define_services: {}
    ports: {}
    service_domain: ''
    type: ClusterIP
  serviceAccount: volcano-admission
  serviceName: ''
  sidecar_container_msg: []
  special_env: {}
  startupProbe:
    content:
      httpGet:
        path: /healthz
        port: https
        scheme: HTTPS
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  strategy: {}
  paddleflow_node_affinity: {}
  tolerations: []
  type: job
  usr_define_msg: {}
