{{- if .Values.csi.enable -}}
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: paddleflowstorage
spec:
  attachRequired: false
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
{{- end -}}