"apiVersion": |-
  storage.k8s.io/v1beta1
"kind": |-
  CSIDriver
"metadata":
  "name": |-
    paddleflowstorage
"spec":
  "attachRequired": !!bool |-
    false
  "podInfoOnMount": !!bool |-
    false
  "volumeLifecycleModes":
  - |-
    Persistent
