"apiVersion": |-
  v1
"binaryData": {}
"data":
  "telegraf.conf": |
    [global_tags]
    {{- if $.Values.pfs_csi_provisioner.logExporter.enable }}
    [agent]
      interval = "{{ .Values.pfs_csi_provisioner.logExporter.telegraf.agent.interval }}"
      metric_batch_size = {{ .Values.pfs_csi_provisioner.logExporter.telegraf.agent.metric_batch_size }}
      metric_buffer_limit = {{ .Values.pfs_csi_provisioner.logExporter.telegraf.agent.metric_buffer_limit }}
      collection_jitter = "0s"
      flush_interval = "{{ .Values.pfs_csi_provisioner.logExporter.telegraf.agent.flush_interval }}"
      flush_jitter = "0s"
      precision = "1s"
      debug = {{ .Values.pfs_csi_provisioner.logExporter.telegraf.agent.debug }}
      hostname = ""
      omit_hostname = false

    [[outputs.prometheus_client]]
      listen = ":{{ .Values.pfs_csi_provisioner.logExporter.port }}"

    {{- range $index_input, $input := .Values.pfs_csi_provisioner.logExporter.telegraf.input }}
    [[inputs.logparser]]
      files = [
                {{- range $index, $file := $input.logFiles }}
                {{- if $index }},{{- end}}
                 "{{ $file }}"
                {{- end }}
              ]
      from_beginning = false
      [inputs.logparser.grok]
        patterns = [
                    {{- range $index, $log := $input.logs }}
                    {{- if $index }},{{- end}}
                    ''{{ $log }}''
                    {{- end }}
                   ]
        measurement = "LogMeasurement"
        #custom_pattern_files = []
        custom_patterns = '''
            {{- range $input.custom_patterns }}
            {{ . }}
            {{- end }}
        '''
    {{- end}}

    [[aggregators.basicstats]]
      namepass = ["LogMeasurement"]
      period = "{{ .Values.pfs_csi_provisioner.logExporter.telegraf.output.period }}"
      drop_original = false
      stats = ["count", "min", "max", "mean", "stdev", "s2", "sum"]

    [[aggregators.histogram]]
      drop_original = false
      reset = true
      [[aggregators.histogram.config]]
        buckets = {{ .Values.pfs_csi_provisioner.logExporter.telegraf.output.buckets }}
        measurement_name = "LogMeasurement"
        fields = [{{ range $index, $value := .Values.pfs_csi_provisioner.logExporter.telegraf.output.histogramFields }}{{if $index}}, {{end}}"{{$value}}"{{end}}]

    [[aggregators.valuecounter]]
      namepass = ["LogMeasurement"]
      period = "{{ .Values.pfs_csi_provisioner.logExporter.telegraf.output.period }}"
      drop_original = false
      fields = [{{ range $index, $value :=  .Values.pfs_csi_provisioner.logExporter.telegraf.output.valuecounterFields }}{{if $index}}, {{end}}"{{$value}}"{{end}}]
    {{- end }}
"kind": |-
  ConfigMap
"metadata":
  "labels":
    "app": |-
      {{ template "pfs-csi-provisioner.pfs_csi_provisioner.fullname" . }}
    "app.kubernetes.io/instance": |-
      {{ $.Release.Name }}
    "app.kubernetes.io/managed-by": |-
      {{ $.Release.Service }}
    "app.kubernetes.io/name": |-
      {{ template "pfs-csi-provisioner.pfs_csi_provisioner.fullname" $ }}
    "chart": |-
      {{ .Chart.Name }}-{{ .Chart.Version }}
    "helm.sh/chart": |-
      {{ $.Chart.Name }}-{{ $.Chart.Version }}
    "heritage": |-
      {{ .Release.Service }}
    "release": |-
      {{ .Release.Name }}
  "name": |-
    {{ template "pfs-csi-provisioner.pfs_csi_provisioner.fullname" . }}
