"apiVersion": |-
  v1
"data": {}
"kind": |-
  Secret
"metadata":
  "labels":
    "app": |-
      {{ template "pfs-csi-provisioner.pfs_csi_provisioner.fullname" . }}
    "app.kubernetes.io/instance": |-
      {{ $.Release.Name }}
    "app.kubernetes.io/managed-by": |-
      {{ $.Release.Service }}
    "app.kubernetes.io/name": |-
      {{ template "pfs-csi-provisioner.pfs_csi_provisioner.fullname" $ }}
    "chart": |-
      {{ .Chart.Name }}-{{ .Chart.Version }}
    "helm.sh/chart": |-
      {{ $.Chart.Name }}-{{ $.Chart.Version }}
    "heritage": |-
      {{ .Release.Service }}
    "release": |-
      {{ .Release.Name }}
  "name": |-
    {{ template "pfs-csi-provisioner.pfs_csi_provisioner.fullname" . }}
