{{- if .Values.paddleflowServer.enable -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: paddleflow-server-config
  namespace: {{ .Release.Namespace }}
data:
  default_pv.yaml: |
    kind: PersistentVolume
    metadata:
      name: pfs-$(pfs.fs.id)-$(namespace)-pv
      annotations:
        pv.kubernetes.io/provisioned-by: paddleflowstorage
    spec:
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Delete
      storageClassName: paddleflowstorage
      capacity:
        storage: 400Gi
      csi:
        driver: paddleflowstorage
        fsType: ext4
        volumeAttributes:
          pfs.fs.id: $(pfs.fs.id)
          pfs.user.name: $(pfs.user.name)
          pfs.server: $(pfs.server)
        volumeHandle: pfs-$(pfs.fs.id)-$(namespace)-pv
  default_pvc.yaml: |
    kind: PersistentVolumeClaim
    metadata:
      name: pfs-$(pfs.fs.id)-pvc
      namespace: $(namespace)
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
      storageClassName: paddleflowstorage
      volumeMode: Filesystem
      volumeName: pfs-$(pfs.fs.id)-$(namespace)-pv
  paddleserver.yaml: |
    database:
      driver: {{ .Values.db.driver }}
      host: {{ .Values.db.host }}
      port: {{ .Values.db.port }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
      database: {{ .Values.db.database }}

    log:
      dir: ./
      filePrefix: log
      level: INFO
      maxKeepDays: 7
      maxFileNum: 7
      maxFileSizeInMB: 100
      isCompress: true

    apiServer:
      host: 0.0.0.0
      port: {{  .Values.paddleflowServer.port  }}
      tokenExpirationHour: {{  .Values.paddleflowServer.tokenExpirationHour  }}

    fs:
      defaultPVPath: "./config/fs/default_pv.yaml"
      defaultPVCPath: "./config/fs/default_pvc.yaml"
      k8sServiceName: "paddleflow-server"
      K8sServicePort: {{  .Values.paddleflowServer.port  }}

    namespaceList:
      - "default"
      - "paddleflow"
    
    job:
      reclaim:
        isCleanJob: true
        isSkipCleanFailedJob: false
        jobTTLSeconds: 600
      schedulerName: {{  .Values.paddleflowServer.schedulerName  }}
      scalarResourceArray:
        - "nvidia.com/gpu"
      defaultJobYamlDir: ./config/server/default/job

    kubeConfig:
      configPath: /home/paddleflow/server/config/server/default/kube.config
      clientQps: 1000
      clientBurst: 1000
      clientTimeout: 0
    
    pipeline: pipeline

    imageRepository:
      server: ""
      namespace: ""
      username: ""
      password: ""
      concurrency: 10
      removeLocalImage: true

    flavour:
      - name: flavour1
        cpu: 1
        mem: 1Gi
{{- end -}}