{{- if .Values.paddleflowServer.enable -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: paddleflow-server-jobyaml-config
  namespace: {{ .Release.Namespace }}
data:
  spark.yaml: |
    apiVersion: sparkoperator.k8s.io/v1beta2
    kind: SparkApplication
    metadata:
      name: sparkName
      namespace: default
    spec:
      driver:
        serviceAccount: spark
      executor:
      image: iregistry.public.com/bmlc/image-packges/spark:pyml-2.8.0
      imagePullPolicy: IfNotPresent
      mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar
      mainClass: org.apache.spark.examples.SparkPi
      mode: cluster
      restartPolicy:
        onSubmissionFailureRetries: 3
        onSubmissionFailureRetryInterval: 5
        type: Never
      sparkConf:
        spark.driver.extraJavaOptions: -Dsun.zip.disableMemoryMapping=true
        spark.executor.extraJavaOptions: -Dsun.zip.disableMemoryMapping=true
        spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version: "2"
      sparkVersion: 3.0.0
      type: Scala
      batchSchedulerOptions:
        queue: default
        priorityClass: normal
  vcjob_collective.yaml: |
    apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
    metadata:
      name: vcJobName
    spec:
      minAvailable: 2
      schedulerName: volcano
      priorityClassName: normal
      policies:
        - event: PodEvicted
          action: RestartJob
      plugins:
        ssh: []
        env: []
        svc: []
      maxRetry: 5
      queue: default
      tasks:
        - replicas: 2
          name: "task"
          template:
            metadata:
              name: templateName
            spec:
              containers:
                - image: collective-container
                  imagePullPolicy: IfNotPresent
                  name: defaultContainer
              restartPolicy: Never
          policies:
            - event: TaskCompleted
              action: CompleteJob
  vcjob_pod.yaml: |
    apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
    metadata:
      name: vcJobName
    spec:
      minAvailable: 1
      schedulerName: volcano
      priorityClassName: normal
      policies:
        - event: PodEvicted
          action: RestartJob
      maxRetry: 5
      queue: default
      tasks:
        - replicas: 1
          name: "task"
          template:
            metadata:
              name: pod
            spec:
              containers:
                - image: nginx
                  imagePullPolicy: IfNotPresent
                  name: container
                  resources:
                    requests:
                      cpu: "1"
              restartPolicy: Never
          policies:
            - event: TaskCompleted
              action: CompleteJob
  vcjob_ps.yaml: |
    apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
    metadata:
      name: vcJobName
    spec:
      minAvailable: 3
      schedulerName: volcano
      priorityClassName: normal
      policies:
        - event: PodEvicted
          action: RestartJob
      plugins:
        ssh: []
        env: []
        svc: []
      maxRetry: 5
      queue: default
      tasks:
        - replicas: 1
          name: "ps"
          ports:
            - ps-port: 8001
          template:
            metadata:
              name: web
            spec:
              containers:
                - image: nginx
                  imagePullPolicy: IfNotPresent
                  name: ps
                  resources:
                    requests:
                      cpu: "1"
              restartPolicy: OnFailure
        - replicas: 2
          name: "worker"
          ports:
            - worker-port: 8001
          template:
            metadata:
              name: web
            spec:
              containers:
                - image: nginx
                  imagePullPolicy: IfNotPresent
                  name: worker
                  resources:
                    requests:
                      cpu: "1"
              restartPolicy: Never
          policies:
            - event: TaskCompleted
              action: CompleteJob

  {{- end -}}