{{- if .Values.paddleflowServer.enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paddleflow-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: paddleflow-server
  replicas: 1
  template:
    metadata:
      labels:
        app: paddleflow-server
    spec:
      containers:
        - name: paddleflow-server
          image: {{ .Values.paddleflowServer.image }}
          resources:
            requests:
              cpu: 1
              memory: 2000Mi
            limits:
              cpu: 1
              memory: 2000Mi
          command: ["/bin/sh"]
          args: ["-c", "cd /home/paddleflow/server && ./paddleflow --k8s-config-path=/home/paddleflow/server/config/server/default/kube.config"]
{{- if .Values.storage_pvc.enable }}
          volumeMounts:
{{- range .Values.pvc }}
            - name: {{ .pvc_name }}
              mountPath: {{ .pvc_point }}
              mountPropagation: HostToContainer
{{- end }}
{{- else }}
          volumeMounts:
{{- end }}
            - name: paddleflow-server-config
              mountPath: /home/paddleflow/server/config/server/default/paddleserver.yaml
              subPath: paddleserver.yaml
            - name: k8s-client-config
              mountPath: /home/paddleflow/server/config/server/default/kube.config
              subPath: kube.config
            - name: paddleflow-server-config
              mountPath: /home/paddleflow/server/config/fs/default_pvc.yaml
              subPath: default_pvc.yaml
            - name: paddleflow-server-config
              mountPath: /home/paddleflow/server/config/fs/default_pv.yaml
              subPath: default_pv.yaml
            - name: paddleflow-server-jobyaml-config
              mountPath: /home/paddleflow/server/config/server/default/job
{{- if .Values.storage_pvc.enable }}
      volumes:
{{- range .Values.pvc }}
        - name: {{ .pvc_name }}
          persistentVolumeClaim:
            claimName: {{ .pvc_name }}
{{- end }}
{{- else }}
      volumes:
{{- end }}
        - name: paddleflow-server-config
          configMap:
            name: paddleflow-server-config
        - name: paddleflow-server-jobyaml-config
          configMap:
            name: paddleflow-server-jobyaml-config
        - name: k8s-client-config
          configMap:
            name: k8s-client-config
{{- end -}}